FROM python:3.14-slim

WORKDIR /code

RUN apt-get update && apt-get install -y \
    libsqlite3-mod-spatialite
ENV SPATIALITE_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/mod_spatialite.so

COPY backend/requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir \
    -r /code/requirements.txt

COPY backend/app /code/app

CMD ["fastapi", "run", "app/main.py", "--proxy-headers", "--port", "8000"]
