import os


class Settings:
    DATABASE_URL = os.environ['DATABASE_URL']

    DNS_NAME = os.environ['DNS_NAME']

    URBIS_PARCEL_BUILDING_GEO_PACKAGE_PATH = os.environ['URBIS_PARCEL_BUILDING_GEO_PACKAGE_PATH']
    URBIS_3D_CONSTRUCTION_GEO_PACKAGE_PATH = os.environ['URBIS_3D_CONSTRUCTION_GEO_PACKAGE_PATH']
